// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using PinturasAPI.Models;

namespace PinturasAPI.Data
{
    public partial class PinturasAPIContext : DbContext
    {
        public PinturasAPIContext()
        {
        }

        public PinturasAPIContext(DbContextOptions<PinturasAPIContext> options)
            : base(options)
        {
        }

        public virtual DbSet<imagen> imagens { get; set; }
        public virtual DbSet<tipo> tipos { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<imagen>(entity =>
            {
                entity.HasOne(d => d.idtipoNavigation)
                    .WithMany(p => p.imagens)
                    .HasForeignKey(d => d.idtipo)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_imagen_tipo");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}