// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PinturasAPI.Models
{
    [Table("imagen")]
    public partial class imagen
    {
        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        public string nombre { get; set; }
        public int idtipo { get; set; }
        [Required]
        [StringLength(200)]
        public string descripcion { get; set; }

        [ForeignKey("idtipo")]
        [InverseProperty("imagens")]
        public virtual tipo idtipoNavigation { get; set; }
    }
}